### ISSUE TITLE
Sw: add -flto

### ISSUE THREAD

**Issue by xobs** [im-tomu/foboot#1]
This compiler flag should save about a kilobyte of data.

**Comment by xobs** [comment]
This has been added now

**Comment by mithro** [comment]
How much did it actually end up saving?

**Comment by futaris** [comment]
Exactly 1000 bytes:

commit c4f9574 [ deps: valentyusb: change url to im-tomu organization ]
$ rm -rf build
$ python3 foboot-bitstream.py --revision hacker
$ du -b build/software/bios/bios.bin
7746	build/software/bios/bios.bin

commit cd6151b [ sw: add -flto to cflags / This reduces codesize by 15% (~1 kB) ]
$ rm -rf build
$ python3 foboot-bitstream.py --revision hacker
$ du -b build/software/bios/bios.bin
6746

**Comment by xobs** [comment]
> Exactly 1000 bytes:
> 
> commit [c4f9574](https://github.com/im-tomu/foboot/commit/c4f95748a6a3789537afc4e6af4f4f3f5ba908f0) [ deps: valentyusb: change url to im-tomu organization ]
> $ rm -rf build
> $ python3 foboot-bitstream.py --revision hacker
> $ du -b build/software/bios/bios.bin
> 7746 build/software/bios/bios.bin

For the record, the bios is also designed to be built without needing to resynthesize the entire bitstream.  If you go into the "sw/" directory and type `make`, it will generate a copy of the bios.  This saves a lot of time for testing and development.
