### ISSUE TITLE
Move to litex defined fomu platform

### ISSUE THREAD

**Issue by TomKeddie** [im-tomu/foboot#2]
I'm just starting to learn litex, seems like somewhere there must be a platform defined for fomu that this can just use.  If there isn't we should create one.

These seem like fairly simple tasks, I'd be happy to take this on.

**Comment by TomKeddie** [comment]
@mithro is there a litex platform/board defined for tomu that you know of?  Thanks.

**Comment by mithro** [comment]
@TomKeddie There are "three" Fomu platforms;
 * Hacker Board (which you get from me)
 * EVT Board (which was [a special thing for the CrowdSupply campaign](https://www.crowdsupply.com/sutajio-kosagi/fomu))
 * Production Board (which will soon ship from [the CrowdSupply campaign](https://www.crowdsupply.com/sutajio-kosagi/fomu))

I'm unsure were @xobs has put his platform files for Foboot (?)

I have the following;
 * [platforms/fomu_evt.py](https://github.com/mithro/litex-buildenv/blob/tinyusb-work/platforms/fomu_evt.py)
 * [platforms/fomu_hacker.py](https://github.com/mithro/litex-buildenv/blob/tinyusb-work/platforms/fomu_hacker.py)

**Comment by mithro** [comment]
@TomKeddie FYI - We should get the `fomu_hacker.py` and `fomu_production.py` these in the upstream LiteX repository....

**Comment by TomKeddie** [comment]
@mithro thanks, foboot defines it all in the one python file (https://github.com/im-tomu/foboot/blob/master/hw/foboot-bitstream.py).  I'll take a look at what you have and try to submit a PR to @xobs to use them.  I'm working towards making foboot more platform independent.

**Comment by mithro** [comment]
@xobs is probably currently very busy with making production happen so he will probably be slow to respond.

**Comment by TomKeddie** [comment]
>  is probably currently very busy with making production happen so he will probably be slow to respond.
Yep, I'm trying to obvious stuff that will be helpful without needing his input.

**Comment by mithro** [comment]
@TomKeddie I'm very supportive of the idea of having Foboot running on Artix-7 and Spartan-6 FPGA hardware.

**Comment by TomKeddie** [comment]
> I'm very supportive of the idea of having Foboot running on Artix-7 and Spartan-6 FPGA hardware.

@mithro thanks.  Once the Trenz releases the design files for Kevin's s7 mini board I'm thinking to re-roll it with a usb connector so he can ship them ready to use instead of needing a ftdi serial cable.  https://twitter.com/bml_khubbard/status/1132725651125837824

**Comment by mithro** [comment]
@TomKeddie Sounds like a great plan!

**Comment by xobs** [comment]
Now that the hardware is more solidified, we can start to integrate parts of `foboot-bitstream.py` into upstream litex.  I was hesitant to do that at first, since it can be difficult to make modifications once something is upstream.

**Comment by xobs** [comment]
This is now how we build things -- using the fomu platform from litex-hub.
