### ISSUE TITLE
Stability after switching to eptri

### ISSUE THREAD

**Issue by rkapuscik** [im-tomu/foboot#26]
We were testing Foboot code in the [usb-test-suite](https://github.com/antmicro/usb-test-suite-build) (see example test output [here](https://travis-ci.com/antmicro/usb-test-suite-build/jobs/261009472)). Software was so far compiled directly via Makefile in `sw` folder, which worked fine since headers there corresponded to the `epfifo` interface.

Recently Foboot master branch switched to `eptri`. I updated the CSR header manually to those output by `foboot_bitstream.py`, but host requests are still NAKed. Looking at signal states, it seems that the `setuphandler_reset_pending` signal is stuck high and  the ISR does not reset it.

Is the code in **usb-eptri.c** stable? Does it work on hardware, or is it still WIP?

**Comment by xobs** [comment]
Thank you for the bug report.  I need to synchronize the `csr.h` in `sw/` with the output from the build system.  I accidentally pushed to master a bit early, but it will replace the older `epfifo` entirely, so I'm not too worried about that.

`usb-eptri` is very stable, and is even supported by upstream tinyusb (https://github.com/hathach/tinyusb/blob/master/src/portable/valentyusb/eptri/dcd_eptri.c).  As a result, there is now the beginnings of a circuitpython port (https://github.com/xobs/circuitpython/releases)

The hardware is now finalized and stabilized, and documented at https://rm.fomu.im/usb.html

I'm slowly going through the USB workshop and adjusting examples so they work with either `usb-epfifo` or `usb-eptri`, depending on the value of `VERSION_MAJOR`: https://rm.fomu.im/version.html#version-major

What isn't stable is the updater.  There are a few corner cases I'm working on fixing, and I'll release a v2.0.2 soon that'll be a release candidate.

**Comment by xobs** [comment]
The workshop is now compatible with both USB endpoints, but focuses mostly on the newer eptri implementation.  Similarly, the v2.0.3 bootloader is stable, and the issues mentioned here have been resolved.
