### ISSUE TITLE
Maximum writable file size through dfu

### ISSUE THREAD

**Issue by sylefeb** [im-tomu/foboot#332]
Hi - I am trying to upload a relatively large file (3MB) into a Fomu PVT (concatenating design and data).
I am aware of issue #330 and the fix, however I am unsure about the maximum size limit:
- the 2.0.4 release message mentions 4MB 
- the dfu upload stops after 1306624 bytes
- the code sets a 1.5MB limit ( https://github.com/im-tomu/foboot/blob/d9a72a8fdedc3e3b6cdc58a9e2cfa82ab8e54f27/sw/src/dfu.c#L40 )
- the flash layout says flash ends at 2MB (https://github.com/im-tomu/foboot/blob/master/doc/FLASHLAYOUT.md)

This overall seems to indicate 2MB flash. However, the PVT bom says 128Mbits ( https://github.com/im-tomu/fomu-hardware/tree/master/archive/pvt ) and the release message mentions 4MB? What would be the expected flash size on the PVT? (of course hoping the limit is conservative and there are a few more bytes after it ;) )

Thanks!

**Comment by xobs** [comment]
The BOM description is incorrect. The "EVT" board had a 128 Mbit SOIC-8 flash part, but production boards used either GD25Q16CEIGR or MX25R1635FZUIH0 (depending on availability), both of which are 16 Mbit.

I've updated the BOM to have the correct description of "IC FLASH 16MBIT SPI/QUAD 8USON".

**Comment by sylefeb** [comment]
Thanks, that clarifies the 2MB limit. (I'll find a way to squeeze the data within the limits)
